team                = "spaces"
project             = "spaces-core"
created_by          = "PedroSpiet"
organization        = "Spaces Inc"
bucket_name = "logo-image-users"
bucket_name_community = "logo-community"